### PR TITLE
Updated package.json

### PR DESCRIPTION
**Pull request by serkansokmen**
Added missing dependency `html-webpack-plugin`

### CODE REVIEW

**Comment by volny** [comment]
Great, thank you for spotting this!

**Comment by serkansokmen** [comment]
No problem @volny :)
Great timesaver, thanks a lot!

**Comment by volny** [comment]
@serkansokmen hi, sorry the project was a bit of a mess before, I fixed a few things and included SASS support. Feel free to update to the new version!

**Comment by serkansokmen** [comment]
Thanks @volny !

**Pull request merged**
